baseURL = "https://swiftirc.net/"
languageCode = "en-us"
title = "SwiftIRC"
theme = "hugo-nuo"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -110

[params]
  email = "support@swiftirc.net"
  github = "SwiftIRC"
