baseURL = "https://swiftirc.net/"
languageCode = "en-us"
title = "SwiftIRC"
theme = "hugo-nuo"
googleAnalytics = "UA-137040075-3"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -110
